### PR TITLE
Turkish language support added

### PR DESCRIPTION
**Pull request by safakesberk**
Turkish language support added. Added new lines and apostrophe problem fixed . There is one commit. Sorry, I couldn't squash. I newbie at git. I am trying to learn.. Is ok now?

### CODE REVIEW

**Comment by safakesberk** [comment]
It's failed again. I don't know why. Can you merge and fix this issue?

**Comment by FallenRiteMonk** [comment]
Ok, I'll take kare about it.

Just for the next time:
to squash just do git rebase -i <the commithash of your first commit>, then squash as in the documentation (setting squash on those commit you want to squash) and keep pick on the commit you want to keep. once you have squashed just do a git push --force then everything should be update on the remote branch and on the pull request.

**Comment by safakesberk** [comment]
Ok, I got it. Thanks for your understanding

**Comment by FallenRiteMonk** [comment]
Hy @safakesberk,

just one more thing, I added you to the README file under contributors. I hope this is all right with you, if not just let me know and I'll remove it.

Greetings
FallenRiteMonk

**Pull request merged**
